#%RAML 1.0
title: test-api

types:
  request: !include request.raml
  response: !include response.raml
  healthcheck: !include healthcheck.raml

/live:
  get:
    displayName: used to check liveness of the api
    responses:
      200:
        body:
          application/json:
            type: healthcheck
/ready:
  get:
    displayName: used to check readiness of the api
    responses:
      200:
        body:
          application/json:
            type: healthcheck
/health:
  get:
    displayName: combined health (liveness and readiness) check
    responses:
      200:
        body:
          application/json:
            type: healthcheck
/api/rate/{quoteID}:
  get:
    responses:
      200:
        body:
          application/json:
            type: request
  post:
    body:
      application/json:
        type: request
    responses:
      200:
        body:
          application/json:
            type: response